# Generated by Django 2.2.7 on 2020-01-03 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_subject_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='due_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='count',
            field=models.IntegerField(),
        ),
    ]
