# Generated by Django 2.2.7 on 2020-01-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200103_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ('due_date',)},
        ),
    ]
